# 100 numpy exercises in Japanese

numpyメーリングリストやStackOverflow、numpyドキュメントから集められたエクササイズのコレクションです。その中から100個選んで作りました。このエクササイズのゴールは、古参ユーザや新しいユーザ両方に対してクイックリファレンスを提供するものです。また、numpyを教える立場の人たちに対しても提供しています。

## 001. [★☆☆] *np*という名前でnumpyパッケージをインポート

In [1]:
import numpy as np

## 002. [★☆☆] numpyのバージョンと設定を表示

In [2]:
print(np.__version__)
# np.show_config()

1.11.1


## 003. [★☆☆] サイズ10のnullベクトルを生成

In [3]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


## 004. [★☆☆] 任意の配列のメモリサイズを表示

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## 005. [★☆☆] コマンドラインからnumpyのadd()のドキュメントを得る

In [5]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

## 006. [★☆☆] サイズ10のゼロベクトルを生成し、5番目の要素に1を入れる

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


## 007. [★☆☆] 10から49までの範囲の値が入ったベクトルを生成する

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 008. [★☆☆] 最初の要素が最後に来るようにベクトルの要素を逆順にする

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## 009. [★☆☆] 0から8の要素が入った$3 \times 3$の行列を生成

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
