# 100 numpy exercises in Japanese

numpyメーリングリストやStackOverflow、numpyドキュメントから集められたエクササイズのコレクションです。その中から100個選んで作りました。このエクササイズのゴールは、古参ユーザや新しいユーザ両方に対してクイックリファレンスを提供するものです。また、numpyを教える立場の人たちに対しても提供しています。

## 001. [★☆☆] *np*という名前でnumpyパッケージをインポート

In [1]:
import numpy as np

## 002. [★☆☆] numpyのバージョンと設定を表示

In [2]:
print(np.__version__)
# np.show_config()

1.11.1


## 003. [★☆☆] サイズ10のnullベクトルを生成

In [3]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


## 004. [★☆☆] 任意の配列のメモリサイズを表示

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## 005. [★☆☆] コマンドラインからnumpyのadd()のドキュメントを得る

In [5]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

## 006. [★☆☆] サイズ10のゼロベクトルを生成し、5番目の要素に1を入れる

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


## 007. [★☆☆] 10から49までの範囲の値が入ったベクトルを生成する

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 008. [★☆☆] 最初の要素が最後に来るようにベクトルの要素を逆順にする

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## 009. [★☆☆] 0から8の要素が入った$3 \times 3$の行列を生成

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 010. [★☆☆] *[1,2,0,0,4,0]*からゼロでない要素のインデックスを表示

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


## 011. [★☆☆] $3 \times 3$の単位行列を生成

In [11]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 012. [★☆☆] ランダムな要素が入っている$3 \times 3 \times 3$の行列を生成

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.88753498  0.55754153  0.82922462]
  [ 0.87557191  0.52332273  0.76070585]
  [ 0.56910979  0.69995267  0.81220256]]

 [[ 0.9803333   0.24775253  0.56679787]
  [ 0.81476369  0.79014595  0.71188133]
  [ 0.47458818  0.47206291  0.30143891]]

 [[ 0.09428887  0.87009431  0.11128753]
  [ 0.15928428  0.19445263  0.03972227]
  [ 0.54373911  0.81021493  0.63565486]]]


## 013. [★☆☆] ランダムな要素の$10 \times 10$行列を生成し、最大値と最小値を表示

In [13]:
Z = np.random.random((10,10))
Zmin = Z.min(); Zmax = Z.max()
print(Zmin, Zmax)

0.00732727743177 0.997863009168


## 014. [★☆☆] サイズ30でランダムな要素のベクトルを生成し、要素の平均値を表示

In [14]:
Z = np.random.random(30)
Zmean = Z.mean()
print(Zmean)

0.506857541563


## 015. [★☆☆] 0のまわりを1が囲むような2次元行列を生成

In [15]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


## 016. [★☆☆] もともとある行列を使って周りを0で囲むような行列を生成

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


## 017. [★☆☆] 以下の式を評価するとどのような結果になるか

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 018. [★☆☆] $5 \times 5$を生成し、要素*[1,2,3,4]*を対角要素より一つ下に入れる

In [18]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 019. [★☆☆] $8 \times 8$の行列を生成し、チェッカーボードパターンとなるよう要素を入れる

In [19]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
