# 100 numpy exercises in Japanese

numpyメーリングリストやStackOverflow、numpyドキュメントから集められたエクササイズのコレクションです。その中から100個選んで作りました。このエクササイズのゴールは、古参ユーザや新しいユーザ両方に対してクイックリファレンスを提供するものです。また、numpyを教える立場の人たちに対しても提供しています。

## 001. [★☆☆] *np*という名前でnumpyパッケージをインポート

In [1]:
import numpy as np

## 002. [★☆☆] numpyのバージョンと設定を表示

In [2]:
print(np.__version__)
# np.show_config()

1.11.1


## 003. [★☆☆] サイズ10のnullベクトルを生成

In [3]:
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


## 004. [★☆☆] 任意の配列のメモリサイズを表示

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## 005. [★☆☆] コマンドラインからnumpyのadd()のドキュメントを得る

In [5]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

## 006. [★☆☆] サイズ10のゼロベクトルを生成し、5番目の要素に1を入れる

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


## 007. [★☆☆] 10から49までの範囲の値が入ったベクトルを生成する

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 008. [★☆☆] 最初の要素が最後に来るようにベクトルの要素を逆順にする

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## 009. [★☆☆] 0から8の要素が入った$3 \times 3$の行列を生成

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 010. [★☆☆] *[1,2,0,0,4,0]*からゼロでない要素のインデックスを表示

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


## 011. [★☆☆] $3 \times 3$の単位行列を生成

In [11]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 012. [★☆☆] ランダムな要素が入っている$3 \times 3 \times 3$の行列を生成

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.87107812  0.80086236  0.67018817]
  [ 0.95884062  0.93050125  0.61722277]
  [ 0.91621588  0.68028839  0.05034147]]

 [[ 0.3950985   0.4092802   0.52953544]
  [ 0.3144707   0.57301456  0.09784126]
  [ 0.17699006  0.40921188  0.7694939 ]]

 [[ 0.36251186  0.55954936  0.94527666]
  [ 0.68527258  0.61953941  0.21304502]
  [ 0.21603525  0.49961274  0.28367565]]]


## 013. [★☆☆] ランダムな要素の$10 \times 10$行列を生成し、最大値と最小値を表示

In [13]:
Z = np.random.random((10,10))
Zmin = Z.min(); Zmax = Z.max()
print(Zmin, Zmax)

0.0089333287272 0.985672739013


## 014. [★☆☆] サイズ30でランダムな要素のベクトルを生成し、要素の平均値を表示

In [14]:
Z = np.random.random(30)
Zmean = Z.mean()
print(Zmean)

0.594439524518


## 015. [★☆☆] 0のまわりを1が囲むような2次元行列を生成

In [15]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


## 016. [★☆☆] もともとある行列を使って周りを0で囲むような行列を生成

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


## 017. [★☆☆] 以下の式を評価するとどのような結果になるか

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 018. [★☆☆] $5 \times 5$を生成し、要素*[1,2,3,4]*を対角要素より一つ下に入れる

In [18]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 019. [★☆☆] $8 \times 8$の行列を生成し、チェッカーボードパターンとなるよう要素を入れる

In [19]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 020. [★☆☆] $6 \times 7 \times 8$の行列において、100番目の要素のインデックス$(x,y,z)$はいくつか

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


## 021. [★☆☆] tileメソッドを用いて$8 \times 8$のチェッカーボードパターンの行列を生成する

In [21]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 022. [★☆☆] ランダムな$5 \times 5$行列を正規化する

In [22]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin) / (Zmax - Zmin)
print(Z)

[[ 0.62732513  0.55855457  0.          0.33840901  0.25704199]
 [ 0.77184203  0.04699147  0.67315418  0.25775669  0.51345665]
 [ 0.01253122  0.08009281  0.25707249  0.10817682  0.30807987]
 [ 0.88887678  0.17872462  0.37899307  0.25171052  0.5133675 ]
 [ 0.93383467  0.05158627  0.484836    1.          0.16546019]]


## 023. [★☆☆] 色を表すような4つの符号なし数値をカスタムdtypeとして生成する

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

## 024. [★☆☆] $5 \times 3$行列と$3 \times 2$行列を掛け合わせる

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


## 025. [★☆☆] 与えられたベクトルについて、3から8までの数値について負数にする

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 026. [★☆☆] 下のスクリプトを実行したらどのような出力が得られるか？

```python
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))
```

In [26]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


## 027. [★☆☆] 整数要素を持つベクトル$Z$について、以下のスクリプトで正しいものは？

```python
Z ** Z
2 << Z >> 2
Z <- Z
1j * Z
Z/1/1
Z<Z>Z
```

In [27]:
import numpy as np

In [28]:
Z ** Z
2 << Z >> 2
Z <- Z
1j * Z
Z/1/1
#Z<Z>Z

array([  0.,   1.,   2.,   3.,  -4.,  -5.,  -6.,  -7.,  -8.,   9.,  10.])

## 028. [★☆☆] 以下のスクリプトの結果はどのようなものになるか？

```python
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
```

In [29]:
#print(np.array(0) / np.array(0))
#print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

[ -9.22337204e+18]


## 029. [★☆☆] 浮動小数点行列からどのように小数点以下切り上げを行うか

In [30]:
Z = np.random.uniform(-10, +10, 10)
print(np.trunc(Z + np.copysign(0.5, Z)))

[  9.   7.   4.  -3.  -8.  -4.   9.  10.  -7.  -5.]
